name: flutter_imin_printer
description: Imin Printer Flutter Plugin
version: 0.0.4
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ezyorder.flutter_imin_printer
        pluginClass: FlutterIminPrinterPlugin

